services:
  web:
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "5000:5000"
    environment:
      - LOCAL_DEV_DB_URI=postgresql://juan_barrera:localdevpass@db:5432/blog_local_dev_db
    depends_on:
      - db


  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=juan_barrera
      - POSTGRES_PASSWORD=localdevpass
      - POSTGRES_DB=blog_local_dev_db

volumes:
  postgres_data: